server:
  port: 8989
spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: pensioner-detail-service
          uri: lb://PENSIONER-SERVICE
          predicates:
            - Path=/api/v1/Pensioner/**
        - id: process-pension-service
          uri: lb://PENSION-SERVICE
          predicates:
            - Path=/api/v1/ProcessPension/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    
